### PR TITLE
Create code scanning workflows on Github Actions

### PR DESCRIPTION
**Pull request by iv0rish**
## Proposed changes

- Apply CodeQL workflow on Github Actions

## Types of changes

Please put an x in the boxes related to your change.

- [ ] Bugfix
- [ ] New feature or enhancement
- [x] Others

## Checklist

*Put an x in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code.*

- [x] I have read the [CONTRIBUTING GUIDELINES](https://github.com/klaytn/caver-java/blob/master/CONTRIBUTING.md) doc
- [x] I have signed the [CLA](https://cla-assistant.io/klaytn/caver-java)
- [x] Lint and unit tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by iv0rish** [comment]
I have read the CLA Document and I hereby sign the CLA

**Review by jimni1222 — APPROVED** [review]

**Comment by iv0rish** [comment]
@jimni1222 I tried to re-run the unit test but keep fails, could you please take a look?

**Comment by jimni1222** [comment]
@iv0rish Can you rebase the latest dev branch? After that if unit test is still fail, i can take a look! If your branch is already on the latest dev branch, also let me know!!

**Comment by iv0rish** [comment]
@jimni1222 PTAL, test has succeed after rebase the branch, thank you!

**Comment by jimni1222** [comment]
@iv0rish This PR seems to contain other commits that are not related to this PR....

**Comment by iv0rish** [comment]
@jimni1222 I've rebased on Github and this may cause the issue.. I will close and re-open the PR again. 🥲

**Pull request closed without merging**
